### ISSUE TITLE
localhost:5984/ unreachable

### ISSUE THREAD

**Issue by utodeb** [dready92/10er10#7]
Bonjour,

Je me permet de parler en français ...

J'essaye d'installer 10er10 mais je n'y arrive pas ;-(
Quand je lance l'install, il m'envoie bouler en me disant 

Setting up 10er10 DEV environment
Hit [Ctrl]-C to abort or wait 5 seconds
localhost:5984/ is unreachable
Configured CouchDB Server unreachable error : 
localhost:5984/ unreachable
stop configuration checks
stop installation process

Pourtant j'arrive à accéder dans mon naviguateur à http://localhost:5984 ...

J'utilise ubuntu 11.04 et couchdb en version 1.0.1 (version des  dépots)

Une idée/conseil ?

Merci

PS : Dans le readme il y a un "Install granphics utilities" je suppose que c'est plutôt "Install graphics utilities"

A+

**Comment by onnlinetool** [comment]
========>>>>>>>>>>>> Telecharger Crack ici

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t
